import 'hex_color.dart';

/// The class "MyColors" defines static variables for colors represented as hexadecimal
/// values.
class MyColors {
  MyColors();

  static final primary = HexColor('#1e3449');
  static final secondary = HexColor('#1c56ff');
  static final white = HexColor('#FFFFFF');
  static final violetBlue = HexColor('#43398E');
  static final darkGray = HexColor('#707070');
  static final gray = HexColor('#8B8989');
  static final darkWhite = HexColor('#F7F7F7');

  // static final blueGreen = HexColor('#30C3A3');
  // static final grayViolet = HexColor('#E5E4EC');
  // static final mediumGray = HexColor('#585858');
  // static final lightGray = HexColor('#CCCCCC');
  // static final blackm = HexColor('#000000');
  // static final black = HexColor('#4F4F4F');
  // static final navyBlue = HexColor("#0094B7");
  // static final lightRed = HexColor('#FF0A1F');
  // static final background = HexColor('#EEEEEE');
  // static final shadow = HexColor('#00000029');
  // static final grayText = HexColor('#8A8A8A');
  // static final yellow = HexColor('#FFE24B');
  // static final grayDarkText = HexColor('#4F4F4F');
  // static final paleGray = HexColor('#E1E4E5');
  // static final red = HexColor('#F22D50');
  // static final transparentViolet = HexColor('#B7B3CF');
  // static final whiteLotion = HexColor("FCFCFC");
  // static final superGrayText = HexColor('#5B5A5A');
  // static final alternativeGrayText = HexColor('#7B7B7B');
  // static final darkGreyTwo = HexColor('#4F4F4F');
  // static final blueGreenDark = HexColor('#037F7F');
  // static final rare = HexColor('#514896');
  // static final paleGrayDark = HexColor('#B0B6B9');
  // static final grayLight = HexColor('#5B5E60');
  // static final graySuppliers = HexColor('#606060');
  // static final backgroundSuppliers = HexColor('#F9F9FC');
  // static final grayDivider = HexColor('#C6C3DD1D');
  // static final paleViolet = HexColor('#F1F0F7');
  // static final paleVioletDouble = HexColor('#DCDAEB');
  // static final grayProviders = HexColor('#FBFAFE');
  // static final paleVioletBorder = HexColor('#ECEAF4');
  // static final mediumBlue = HexColor('#319AF3');
  // static final lightViolet = HexColor('#EAE8F5');
  // static final darkViolet = HexColor('#3A3180');
  // static final lightVioletBackground = HexColor('#FEFDFF');
  // static final extraLightGray = HexColor('#a6a6a7');
  // static final cleanGray = HexColor('#c9c9c9');
  // static final whiteOpaque = HexColor('#E8E7F2');
  // static final shadingFlag = HexColor('#A09BC6');
  // static final whiteShading = HexColor('#665EA3');
  // static final darkCountry = HexColor('#545454');
  // static final grayWhite = HexColor('#FAFAFA');
  // static final grayVeryLight = HexColor('#F8F8F8');
  // static final ghostWhite = HexColor('#FBFAFF');
  // static final paleWhiteBlue = HexColor('#E2E1EF');
  // static final grayExtraLight = HexColor('#D5D5D5');
  // static final lightBlue = HexColor('#231F20');
  // static final sellersFont = HexColor('#292730');
  // static final darkGrayTextField = HexColor('#656565');
  // static final graphite = HexColor('#292730');
  // static final neutralGray = HexColor('#6E6E6E');
  // static final smokeGray = HexColor('#B4B4B4');
  // static final darkYellow = HexColor('#FFE473');
  // static final pastelYellow = HexColor('#FFFAE7');
  // static final softYellow = HexColor('##FFE275');
  // static final pastelGreen = HexColor('#ECFFFB');
  // static final pastelViolet = HexColor('#EFECFF');
  // static final grayOpaque = HexColor('#858393');
  // static final grayWhiteOpaque = HexColor('#F0EFF6');
  // static final violetOpaque = HexColor('#7D77B1');
  // static final grayviolet = HexColor('#F1F0F7C6');
  // static final lightText = HexColor('#929292');
  // static final mediumViolet = HexColor('#CDC7F0');
  // static final mediumYellow = HexColor('#FFE275');
  // static final slateGray = HexColor('#6b6b6b');
  // static final grayShadow = HexColor('#DADADB');
  // static final grayPop = HexColor('#CFCFCF');
  // static final aticlesBackgroundGray = HexColor("#F5F4FC");
  // static final coralOrange = HexColor('#F9744B');
  // static final khakiOrange = HexColor("#FFE375");
  // static final softLavender = HexColor('#D6D3E8');
  // static final darkSlate = HexColor('#3F3F41');
  // static final mistyGray = HexColor('#E0E4E6');
  // static final paleLilac = HexColor('#EBE8F5');
}
